//sprsht v1.2.2
/*
Copyright (C) 2007 norman a bakker

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Library General Public
    License as published by the Free Software Foundation; either
    version 2 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Library General Public License for more details.

    You should have received a copy of the GNU Library General Public
    License along with this library; if not, write to the Free
    Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
*/
/*
static const Fl_Menu_Item bottomtable[] = {
    {"Start",	 0,         	0, (void*) 2},
    {"Rerun",	 0,        		0, (void*) 4},
	{0},
}; */

static const Fl_Menu_Item menutable[] = {
	//main menu
  	{"File",0,0,0,FL_SUBMENU},
    {"New",	FL_CTRL+'n',         	0, (void*) 20,FL_MENU_DIVIDER},
    {"All sheets :", 0,0,0,FL_MENU_DIVIDER},
  //  {"Open uncompacted",	FL_CTRL+'o',        0, (void*) 22},
    {"Open", 0,0,(void*) 23},
    {"Re open", 0,0, (void*) 24},
	//{"Save uncompacted", FL_CTRL+'s',0, (void*) 26},
	{"Save", 0,0, (void*) 25},
	{"Save uncompressed", FL_CTRL+'s',0, (void*) 27},
	{"Save as",   FL_ALT+'s',   0, (void*) 28,FL_MENU_DIVIDER},
    {"Single sheet :", 0,0,0,FL_MENU_DIVIDER},
	//{"Save to string",	0, 0, (void*) 29},
   // {"Read from string",0, 0, (void*) 30},
    {"Open", 0,0, (void*) 32},
    {"Re open", 0,0, (void*) 34},
	{"Print (csv copy)",       		0 , 0, (void*) 40,FL_MENU_DIVIDER},
	{"CLEAR ALL",       			0 , 0, (void*) 45,FL_MENU_DIVIDER},											
    {"Quit",	FL_CTRL+'q',        0 ,(void*) 50},
    {0},
	{"Edit",FL_ALT+'e',0,0,FL_SUBMENU},
  	{"Cut",			FL_CTRL+'x',	0,	  (void *) 105},
 	{"Copy",		FL_CTRL+'c',	0, 	  (void *) 110},
 	{"Paste values",FL_CTRL+'v',    0, 	  (void *) 115},
  	{"Paste all",	FL_CTRL+'a',	0, 	  (void *) 120},
  	{"Undo input",	FL_ALT+'u',	    0, 	  (void *) 121},
  	{"Redo input",	FL_CTRL+'u',	0, 	  (void *) 122},
	{"extend cell references on first/first 2 cells",FL_ALT+'s', 0, (void *) 440},
	{"extend numbers in first/first 2 cells",0, 0, (void *) 442},
	{"Clear values and reset formats",	0,	0, (void*) 125, FL_MENU_DIVIDER},
	{"Preferences",		0, 0, 0,FL_SUBMENU },
	//{"initial number of sheets",0, 0,  (void *) 18},
	{"no of rows",			0, 0, (void*) 	150 },
	{"no of columns",		0, 0, (void*) 	151 },
	{"save in rows",		0, 0, (void*)	152 },
	{"save in columns",		0, 0, (void*)	153 },
	{"save uncompressed",	0, 0, (void*) 	154 },
	{"row height", 			0, 0, (void*)   156 ,  FL_MENU_DIVIDER},
	{"column width",		0, 0, (void*)   157  },
	{"row header width",    0, 0, (void*)   158  },
	{"col header height",   0, 0, (void*)   160  },
	{"width scale factor",  0, 0, (void*)   162  }, //fudges for use with autocell size
	{"height scale factor", 0, 0, (void*)   164  },
	{"header colour",   	0, 0, (void*)   166  },
	{"header text colour",  0, 0, (void*)   168  },
	{"background colour",   0, 0, (void*)   170  },
	{"selection colour",    0, 0, (void*)   172  },
	{"default colours",  	0, 0, (void*)   174  },
	{"A-Z column labels",   0, 0, (void*)   176  },
  //  {"soft cell boundary",	0, 0, (void*)   177  },
	{" ",                   0, 0, (void*)   178  },
	{0},
    {0},
 	{"View",				0,0,0, FL_SUBMENU},
	{"&goto cell",			FL_ALT+'g', 0, (void*) 60, FL_MENU_DIVIDER},
	//{"ALL : ",				0,			0, 0,  FL_MENU_DIVIDER},
	//{"formula evaluation",  FL_CTRL+FL_ALT+'=',  0, (void*)  61},
	{"clear flags", 	0,					 0, (void*)  62},
	//{"lock all",            FL_CTRL+FL_ALT+'a',  0, (void*)  63},
	//{"unlock all",          FL_CTRL+FL_ALT+'u',	 0, (void*)  64},
	//{"hide all",            0, 					 0, (void*)  65},
	//{"unhide all",          0, 					 0, (void*)  66},
    {"default view", 		0,					 0, (void*)  67},
	{"clear drawings",  0,                   0, (void*)	 68, FL_MENU_DIVIDER},
	//{"SELECTION : y/n ",	0, 		 0,          0,  FL_MENU_DIVIDER},
    {"formula evaluation",  FL_ALT+'=', 0, (void*) 140},
    {"0",	FL_ALT+'0',		   0, (void *)141},
    {"+",	FL_ALT+'+',	       0, (void *)142},
	{"colour -",FL_ALT+'-',	   0, (void *)144},
    {",",FL_ALT+',',	       0, (void *)146},
    {"toggle digits/precision",FL_ALT+'.',	   0, (void *)147},
    {"currency",FL_ALT+'$',	   0, (void *)148},
	{"lock",				   0, 0, (void*)	402},
	{"unlock",				   0, 0, (void*)	403},
	{"hide",			       0, 0, (void*)    404},
	{"unhide",				   0, 0, (void*)	405, FL_MENU_DIVIDER},
	//{"set special drawflag",   0, 0, (void*)	406},
	//{"clear special drawflag", 0, 0, (void*)    407},
	{"set nodraw flag", 	   0, 0, (void*)	408},
	{"clear nodraw flag",      0, 0, (void*)    409},
    {"format numbers",  FL_ALT+'#',	   0, (void *)149, FL_MENU_DIVIDER},
	{"column width in pixels", 0,    0, (void*) 208},
	{"auto column width",FL_ALT+'w', 0, (void*) 210},
	{"auto row height",FL_ALT+'h',   0, (void*) 212},
	{"auto width/height",	 	  0, 0, (void*) 214},
    {0},
 	{"Format", 					0, 0, 0, FL_SUBMENU},
 	{"selection : ",			0, 0, 0,  FL_MENU_DIVIDER},
  	{"Default format", 			0, 0, (void*)   200},
	{"C_style format",			0, 0, (void*) 	206},
	{"clear C_style format",	0, 0, (void*) 	207},
	{"merge cells",	       	  	0, 0, (void*)   MERGE},
	{"Standard fonts",			0, 0, 0,	FL_SUBMENU},
	{"helvetica", 				0, 0, (void*) 	230},
	{"helvetica bold", 			0, 0, (void*)	231},
	{"helvetica italic", 		0, 0, (void*)	232},
	{"helvetica bold italic", 	0, 0, (void*)	233},
	{"courier", 				0, 0, (void*)	234},
	{"courier bold", 			0, 0, (void*)	235},
	{"courier italic", 			0, 0, (void*)	236},
	{"courier bold italic", 	0, 0, (void*)	237},
	{"times", 					0, 0, (void*)	238},
	{"times bold", 				0, 0, (void*)	239},
	{"times italic", 			0, 0, (void*)	240},
	{"times bold italic", 		0, 0, (void*)	241},
	{"symbol", 					0, 0, (void*)	242},
	{"screen", 					0, 0, (void*)	243},
	{"screen bold", 			0, 0, (void*)	244, FL_MENU_DIVIDER},
	{"system fonts <0-255>", 			0, 0, (void*)	245},
	{0},
	//{"Show system wide fonts",		0, 0, (void*) 55},//			FL_SUBMENU},
	//{"select font and size",	0, 0, (void*) 	55},
	//{"apply font and size to selection",0,0,(void*) 56},
	//{0},
	{"Font size",				0, 0, 0,			FL_SUBMENU},
	{" 8",						0, 0, (void*)   270},
	{"10",						0, 0, (void*)	271},
	{"12",						0, 0, (void*)	272},
	{"14",						0, 0, (void*)	273},
	{"16",						0, 0, (void*)	274},
	{"18",						0, 0, (void*)	275},
	{"20",						0, 0, (void*)	276},
	{"30",						0, 0, (void*)	277},
	{"40",						0, 0, (void*)	278},
	{"custom",					0, 0, (void*)	279},
	{0},
	{"Align",		FL_ALT+'a',	0, 0,				FL_SUBMENU},
	{"align_center",  			0, 0, (void*)   280},					// 0,
	{"align_top",				0, 0, (void*)   281},					// 1,
	{"align_bottom",			0, 0, (void*)   282},					// 2,
	{"align_left",				0, 0, (void*)   283},					// 4,
	{"align_right",				0, 0, (void*)   284},					// 8,
	{"align_inside",			0, 0, (void*)   285},					// 16,
	{"align_text_over_image",	0, 0, (void*)   286},					// 32,
	{"align_image_over_text",	0, 0, (void*)   287},					// 0,
	{"align_clip",				0, 0, (void*)   288},					// 64,
	{"align_wrap",				0, 0, (void*)   289},					// 128,
	{"align_top_left",			0, 0, (void*)   290},					// fl_align_top | fl_align_left,
	{"align_top_right",			0, 0, (void*)   291},					// fl_align_top | fl_align_right,
	{"align_bottom_left",		0, 0, (void*)   292},					// fl_align_bottom | fl_align_left,
	{"align_bottom_right",		0, 0, (void*)   293},					// fl_align_bottom | fl_align_right,
	{"align_nowrap",			0, 0, (void*)   294},					// 0  for back compatability1
	{0},
	{"Colour", 					0, 0, 0, 			FL_SUBMENU},
	{"colour map",				0, 0, (void*)   295},
	{"custom",					0, 0, (void*)   296},
	{"show colour value",		0, 0, (void*)   297},
	{0},
	{"Background Colour", 		0, 0, 0, 			FL_SUBMENU | FL_MENU_DIVIDER},
	{"colour map",				0, 0, (void*)   302},
	{"custom",					0, 0, (void*)   303},
	{0},
	{"Precision",				0, 0, 0,			FL_SUBMENU},
	{"selected columns : ",				0, 0, 0,  FL_MENU_DIVIDER},
	{"0",						0, 0, (void*)	310},
	{"2",						0, 0, (void*)	311},
	{"4",						0, 0, (void*)	312},
	{"6",						0, 0, (void*)	313},
	{"8",						0, 0, (void*)	314},
	{"10",						0, 0, (void*)	315},
	{"12",						0, 0, (void*)	316},
	{"custom",					0, 0, (void*)	317},
	{0},
	{0},
  	{"Tools", 					0, 0, 0, 		FL_SUBMENU},
	{"Add a user constant",     0, 0, (void*)   400},
	{"show colour value",		0, 0, (void*)   411},
	//{"show boxtypes",			0, 0, (void*)   412},
	//{"load an image",			0, 0, (void*)	413},
	//{"browse file",				0, 0, (void*)	414},
	{"send input file to stdout", 0, 0, (void*) 430, FL_MENU_DIVIDER},
    {"fill all with numbers",	0, 0, (void *)  431},
	{"selection with numbers",	FL_ALT+'t', 0, (void *)  432},
	{"fill based on first or first 2 cells",FL_ALT+'s', 0, (void *) 440, FL_MENU_DIVIDER},
    {"test a function",	        0 ,0, (void*)   460},
   // {"pop up window",			0, 0, (void*)   470},
    {0},
	{"Inserts",				0, 0, 0, FL_SUBMENU},
	{"merge cells",	       	  	0, 0, (void*)  MERGE},
	{"pixmap",	       			0, 0, (void*)  PIXMAP},
	{"comment box",				0, 0, (void*)  COMMENT},
	{"picture",					0, 0, (void*)  PICTURE},
	{"Drawing",					0, 0, 0,   FL_SUBMENU},
	{"horizontal line",			0, 0, (void*)  HORIZLINE},
	{"vertical line",			0, 0, (void*)  VERTLINE},
	{"rectangle",				0, 0, (void*)  RECTANGLE},
	{"Formats",					0, 0, 0, FL_SUBMENU},
	{"Line types", 				0, 0, 0, FL_SUBMENU | FL_MENU_DIVIDER},
	{"solid",					0, 0, (void*)   304},
	{"dash",					0, 0, (void*)   305},
	{"dot",						0, 0, (void*)   306},
	{0},
	{"Line width", 				0, 0, (void*)   307},
	{"Line colour", 			0, 0, (void*)   308},
	{"Fill colour",				0, 0, (void*)	309},
	{"Text format",				0, 0, 0, FL_SUBMENU | FL_MENU_DIVIDER},
	{"color",					0, 0, (void*)   320},
	{"size",					0, 0, (void*)   321},
	{"font",					0, 0, (void*)   322},
	{0},
	{0},
	{0},
	{"Show,hide,delete,edit",	0, 0, 0, 	FL_SUBMENU},
	{"display all in range",	0, 0, (void*)   SHOWALL},
	{"hide all in range", 		0, 0, (void*)	HIDEALL},
	{"display comments",			0, 0, (void*)	SHOWCOMMENTS},
	{"hide comments", 			0, 0, (void*)	HIDECOMMENTS},
	{"delete all in range",	 	0, 0, (void*)   DELETEALL},
	{"delete comments",			0, 0, (void*)	DELETECOMMENTS},
	{"show map entries in range",0,0, (void*)	SHOWMAP},
	{"edit/delete map entries",	0, 0, (void*)   EDITMAP},
	{"print all map entries on stdout",0,0,(void*)LISTALL},
    {0},
    {0},
    {"Help",					0,  0, 0, 		FL_SUBMENU},
    {"Introduction",			0,  0, (void*) 710},
	{"Quick guide",				0,  0, (void*) 720},
    {"File",					0,  0, (void*) 730},
    {"Edit",					0,  0, (void*) 740},
    {"View",					0,  0, (void*) 745},
    {"Format",					0,  0, (void*) 750},
    {"Tools",					0,  0, (void*) 760},
	{"Inserts",				0,  0, (void*) 765 , FL_MENU_DIVIDER},
	{"right mouse click",       0,  0, (void*) 770 , FL_MENU_DIVIDER},
    {"About",					0,  0, (void*) 799},
    {0},
	{"User functions",	    0,0,0, 				FL_SUBMENU},
 	//{"check run",     	 	FL_ALT+'z', 0, (void*) current_function},//TODO used to provide a global short cut key for user fns
	{"home loan",		   	0, 0, (void*) 	800},  //600 700 for user
	{"pipeflow",		0, 0, (void*) 	810},
    {"pipenetwork",   0, 0, (void*)   812},

	{"",					0, 0, (void*) 	802},
	{ss->temptest.c_str(),	0, 0, (void*) 	803},
	{"run something4",		0, 0, (void*) 	804},
	{"run something5",		0, 0, (void*) 	805},
	{"run something6",		0, 0, (void*) 	806},
	{"run something7",		0, 0, (void*) 	807},
	{0},

   	{"Run",     	 		FL_ALT+'z', 0, (void*) current_function},

	{"Zoom",				0, 0, 0, FL_SUBMENU },
	{"40%",  				0, 0, (void*)  71, FL_MENU_RADIO},
	{"60%",  				0, 0, (void*)  72, FL_MENU_RADIO},
	{"80%",  				0, 0, (void*)  73, FL_MENU_RADIO},
	{"90%",  				0, 0, (void*)  74, FL_MENU_RADIO},
	{"100%",  				0, 0, (void*)  75, FL_MENU_RADIO},
	{"110%",  				0, 0, (void*)  76, FL_MENU_RADIO},
	{"120",					0, 0, (void*)  77, FL_MENU_RADIO},
	{"140%",  				0, 0, (void*)  78, FL_MENU_RADIO | FL_MENU_DIVIDER},
	{"custom",				0, 0, (void*)  79, FL_MENU_DIVIDER },
    {"default zoom",		0, 0, (void*)  80}, 
	{0},

 // "Sheet menu gets added here in sprsht.cxx
	{0},

};

Fl_Menu_Item rightclick[] = {
	//right click menu
	// fair amount of duplication here, probably could be done more efficiently
  	{"Cut",			FL_CTRL+'x',	0,	  (void *) 105},
 	{"Copy",		FL_CTRL+'c',	0, 	  (void *) 110},
 	{"Paste relative values",FL_CTRL+'r',0, (void *) 112},
 	{"Paste values",FL_CTRL+'v', 0, 	  (void *) 115},
  	{"Paste all",FL_CTRL+'e',	0, (void *) 120,	FL_MENU_DIVIDER},
  	{"Undo input",	FL_ALT+'u',	0, (void *) 121},
  	{"Redo input",	FL_CTRL+'u',	0, 	  (void *) 122},
	{"fill based on first or first 2 cells",FL_ALT+'s', 0, (void *) 440, FL_MENU_DIVIDER},
    {"Rows, Columns",			0, 0, 0, FL_SUBMENU},
	{"add rows ",				0, 0, (void *) 130},
	{"add columns",				0, 0, (void *) 131},
	{"delete rows", 			0, 0, (void *) 136},
	{"delete columns",			0, 0, (void *) 138},
	{0},
	{"Delete",					0 , 0,0 ,           FL_SUBMENU},
	{"delete values", 			FL_ALT+'d', 0, (void *) 134},
	{0},
	{"Format", 					0, 0, 0, 			FL_SUBMENU},
  	{"Default format", 			0, 0, (void*)   200},
	{"C_style format (selcn)",	0, 0, (void*) 	206},
	{"clear C_style format (selcn)",	0, 0, (void*) 	207},
	{"column width in pixels",		0, 0, (void*)   208},
	{"auto column width",		FL_ALT+'w', 0, (void*) 	210},
	{"auto row height",			FL_ALT+'h', 0, (void*) 	212},
	{"auto width/height", 				0, 0, (void*) 	214},
	{0},
	{"Standard fonts",					0, 0, 0,	FL_SUBMENU},
	{"helvetica", 				0, 0, (void*) 	230},
	{"helvetica bold", 			0, 0, (void*)	231},
	{"helvetica italic", 		0, 0, (void*)	232},
	{"helvetica bold italic", 	0, 0, (void*)	233},
	{"courier", 				0, 0, (void*)	234},
	{"courier bold", 			0, 0, (void*)	235},
	{"courier italic", 			0, 0, (void*)	236},
	{"courier bold italic", 	0, 0, (void*)	237},
	{"times", 					0, 0, (void*)	238},
	{"times bold", 				0, 0, (void*)	239},
	{"times italic", 			0, 0, (void*)	240},
	{"times bold italic", 		0, 0, (void*)	241},
	{"symbol", 					0, 0, (void*)	242},
	{"screen", 					0, 0, (void*)	243},
	{"screen bold", 			0, 0, (void*)	244},
	{" ", 						0, 0, (void*)	-1},
	{"system fonts between 0-255", 			0, 0, (void*)	245}, //will pick up system fonts
	{0},
	{"Font size",				0, 0, 0,			FL_SUBMENU},
	{" 8",						0, 0, (void*)   270},
	{"10",						0, 0, (void*)	271},
	{"12",						0, 0, (void*)	272},
	{"14",						0, 0, (void*)	273},
	{"16",						0, 0, (void*)	274},
	{"18",						0, 0, (void*)	275},
	{"20",						0, 0, (void*)	276},
	{"22",						0, 0, (void*)	277},
	{"24",						0, 0, (void*)	278},
	{"custom",					0, 0, (void*)	279},
	{0},
	{"Align",		FL_ALT+'a',	0, 0,				FL_SUBMENU},
	{"align_center",  			0, 0, (void*)   280},					// 0,
	{"align_top",				0, 0, (void*)   281},					// 1,
	{"align_bottom",			0, 0, (void*)   282},					// 2,
	{"align_left",				0, 0, (void*)   283},					// 4,
	{"align_right",				0, 0, (void*)   284},					// 8,
	{"align_inside",			0, 0, (void*)   285},					// 16,
	{"align_text_over_image",	0, 0, (void*)   286},					// 32,
	{"align_image_over_text",	0, 0, (void*)   287},					// 0,
	{"align_clip",				0, 0, (void*)   288},					// 64,
	{"align_wrap",				0, 0, (void*)   289},					// 128,
	{"align_top_left",			0, 0, (void*)   290},					// fl_align_top | fl_align_left,
	{"align_top_right",			0, 0, (void*)   291},					// fl_align_top | fl_align_right,
	{"align_bottom_left",		0, 0, (void*)   292},					// fl_align_bottom | fl_align_left,
	{"align_bottom_right",		0, 0, (void*)   293},					// fl_align_bottom | fl_align_right,
	{"align_nowrap",			0, 0, (void*)   294},					// 0  for back compatability1
	{0},
	{"Colour", 					0, 0, 0, 			FL_SUBMENU },
	{"colour map",				0, 0, (void*)   300},
	{"custom",					0, 0, (void*)   301},
	{0},
	{"Background Colour", 		0, 0, 0, 			FL_SUBMENU | FL_MENU_DIVIDER},
	{"colour map",				0, 0, (void*)   302},
	{"custom",					0, 0, (void*)   303},
	{0},
	{"Precision",				0, 0, 0,			FL_SUBMENU},
	{"selected columns : ",				0, 0, 0,  FL_MENU_DIVIDER},
	{"0",						0, 0, (void*)	310},
	{"2",						0, 0, (void*)	311},
	{"4",						0, 0, (void*)	312},
	{"6",						0, 0, (void*)	313},
	{"8",						0, 0, (void*)	314},
	{"10",						0, 0, (void*)	315},
	{"12",						0, 0, (void*)	316},
	{"custom",					0, 0, (void*)	317},
	{0},
  	{"Tools", 					0, 0, 0, 		FL_SUBMENU},
	{"Add a user constant",     0, 0, (void*) 400},
	{"send input file to stdout", 0, 0, (void*) 430, FL_MENU_DIVIDER},
    {"fill all with numbers",	0, 0, (void *)  431},
	{"selection with numbers",	FL_ALT+'t', 0, (void *)  432},
	{"fill based on first or first 2 cells",FL_ALT+'s', 0, (void *) 440, FL_MENU_DIVIDER},
    {"test a function",			0 ,0, (void*)   460},
    {0},
};

Fl_Menu_Item help_pages[] = {
	{"run something 0",		0, 0, (void*) 	600},  //500 to 600 for user
	{"run something1",		0, 0, (void*) 	601},
	{"run something2",		0, 0, (void*) 	602},
	{"run something3",		0, 0, (void*) 	603},
	{"run something4",		0, 0, (void*) 	604},
	{"run something5",		0, 0, (void*) 	605},
	{"run something6",		0, 0, (void*) 	606},
	{"run something7",		0, 0, (void*) 	607},
	{0},
};

